cruise-pack:
  work-dir: ''
  # 'system', 'cross-platform', 'intellij', 'darcula', fully qualified class name ex. 'javax.swing.plaf.metal.MetalLookAndFeel', 'javax.swing.plaf.nimbus.NimbusLookAndFeel', 'com.sun.java.swing.plaf.motif.MotifLookAndFeel'
  look-and-feel: system
  font:
  font-size: 14
  window-padding: 5
  document-files-warning-threshold: 10
  document-files-error-threshold: 50
  ui: true

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail_on_empty_beans: false
    property-naming-strategy: SNAKE_CASE
  main:
    banner-mode: log