cruise-pack:
  work-dir: ''
  # 'system', 'cross-platform', fully qualified class name ex. 'javax.swing.plaf.metal.MetalLookAndFeel', 'javax.swing.plaf.nimbus.NimbusLookAndFeel', 'com.sun.java.swing.plaf.motif.MotifLookAndFeel'
  look-and-feel: system

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail_on_empty_beans: false